# Generated by Django 2.2.3 on 2019-07-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, null=True, verbose_name='ID')),
                ('hair_color', models.CharField(choices=[('0', 'ダークブラウン'), ('1', 'ダークブロンド'), ('2', 'ブラウン'), ('3', 'ブラウン'), ('4', 'ブロンド'), ('5', '黒色'), ('6', '赤色')], max_length=20, null=True, verbose_name='髪の色')),
                ('height', models.CharField(choices=[('0', '-159'), ('1', '160-169'), ('2', '170-179'), ('3', '180-189'), ('4', '190-')], max_length=20, null=True, verbose_name='身長(cm)')),
                ('weight', models.CharField(choices=[('0', '-50'), ('1', '50-59'), ('2', '60-69'), ('3', '70-79'), ('4', '80-89'), ('5', '90-')], max_length=20, null=True, verbose_name='体重(kg)')),
                ('ICI_IUI', models.CharField(choices=[('0', 'ICI-未洗浄'), ('1', 'IUI-洗浄済')], max_length=20, null=True, verbose_name='ICI/IUI')),
                ('blood_type', models.CharField(choices=[('0', 'A-'), ('1', 'A+'), ('2', 'AB-'), ('3', 'AB+'), ('4', 'B-'), ('5', 'B+'), ('6', 'O-'), ('7', 'O+')], max_length=20, null=True, verbose_name='血液型')),
                ('today_photo', models.CharField(choices=[('0', 'いいえ'), ('1', 'はい')], max_length=20, null=True, verbose_name='現在の写真')),
                ('profile', models.CharField(choices=[('0', 'ドナー独占権'), ('1', '基本'), ('2', '詳細')], max_length=20, null=True, verbose_name='プロフィール')),
                ('eye_color', models.CharField(choices=[('0', '灰色'), ('1', '青色'), ('2', '青色\x08/灰色'), ('3', '青色/緑色'), ('4', '茶色'), ('5', '茶色/灰色'), ('6', '茶色/緑色'), ('7', '緑色'), ('8', '緑色/灰色')], max_length=20, null=True, verbose_name='瞳の色')),
                ('mot', models.CharField(choices=[('0', 'MOT5'), ('1', 'MOT10'), ('2', 'MOT20'), ('3', 'MOT30'), ('4', 'MOT40'), ('5', 'MOT50+')], max_length=20, null=True, verbose_name='運動能力')),
                ('memo', models.TextField(max_length=200)),
            ],
        ),
    ]
