# Generated by Django 2.2.3 on 2019-07-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='eye_color',
            field=models.CharField(choices=[('0', '灰色'), ('1', '青色'), ('2', '青色\x08/灰色'), ('3', '青色/緑色'), ('4', '茶色'), ('5', '茶色/灰色'), ('6', '茶色/緑色'), ('7', '緑色'), ('8', '緑色/灰色')], max_length=20, null=True, verbose_name='瞳の色'),
        ),
    ]
