# Generated by Django 2.2.3 on 2019-07-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='first_name',
        ),
        migrations.AddField(
            model_name='donor',
            name='ICI_IUI',
            field=models.CharField(choices=[('0', 'ICI-未洗浄'), ('1', 'IUI-洗浄済')], default='', max_length=20, verbose_name='ICI/IUI'),
        ),
        migrations.AddField(
            model_name='donor',
            name='eye_color',
            field=models.CharField(choices=[('0', '灰色'), ('1', '青色'), ('2', '青色\x08/灰色'), ('3', '青色/緑色'), ('4', '茶色'), ('5', '茶色/灰色'), ('6', '茶色/緑色'), ('7', '緑色'), ('8', '緑色/灰色')], default='', max_length=20, verbose_name='瞳の色'),
        ),
        migrations.AddField(
            model_name='donor',
            name='hair_color',
            field=models.CharField(choices=[('0', 'ダークブラウン'), ('1', 'ダークブロンド'), ('2', 'ブラウン'), ('3', 'ブラウン'), ('4', 'ブロンド'), ('5', '黒色'), ('6', '赤色')], default='', max_length=20, verbose_name='髪の色'),
        ),
        migrations.AddField(
            model_name='donor',
            name='height',
            field=models.CharField(choices=[('0', '-159'), ('1', '160-169'), ('2', '170-179'), ('3', '180-189'), ('4', '190-')], default='', max_length=20, verbose_name='身長(cm)'),
        ),
        migrations.AddField(
            model_name='donor',
            name='mot',
            field=models.CharField(choices=[('0', 'MOT5'), ('1', 'MOT10'), ('2', 'MOT20'), ('3', 'MOT30'), ('4', 'MOT40'), ('5', 'MOT50+')], default='', max_length=20, verbose_name='運動能力'),
        ),
        migrations.AddField(
            model_name='donor',
            name='number',
            field=models.CharField(default='', max_length=20, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='donor',
            name='profile',
            field=models.CharField(choices=[('0', 'ドナー独占権'), ('1', '基本'), ('2', '詳細')], default='', max_length=20, verbose_name='プロフィール'),
        ),
        migrations.AddField(
            model_name='donor',
            name='today_photo',
            field=models.CharField(choices=[('0', 'いいえ'), ('1', 'はい')], default='', max_length=20, verbose_name='現在の写真'),
        ),
        migrations.AddField(
            model_name='donor',
            name='weight',
            field=models.CharField(choices=[('0', '-50'), ('1', '50-59'), ('2', '60-69'), ('3', '70-79'), ('4', '80-89'), ('5', '90-')], default='', max_length=20, verbose_name='体重(kg)'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_type',
            field=models.CharField(choices=[('0', 'A-'), ('1', 'A+'), ('2', 'AB-'), ('3', 'AB+'), ('4', 'B-'), ('5', 'B+'), ('6', 'O-'), ('7', 'O+')], default='', max_length=20, verbose_name='血液型'),
        ),
    ]
