# Generated by Django 2.2.5 on 2019-09-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190921_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='defo_picture', upload_to='images/'),
        ),
    ]
