# Generated by Django 2.2.5 on 2019-09-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190925_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, choices=[('0', '内容がない'), ('1', '科学'), ('2', '思考'), ('3', 'プログラミング'), ('4', '出来事')], max_length=10),
        ),
    ]
