# Generated by Django 2.2.5 on 2019-09-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20190926_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sumnail',
            field=models.ImageField(default='defo_picture', upload_to='images/'),
        ),
    ]
